/*=========================================================================================
    File Name: query-string.js
    Description: internationalization library set language using query string
    --------------------------------------------------------------------------------------
    Item Name: Robust - Responsive Admin Theme
    Version: 1.2
    Author: PIXINVENT
    Author URL: http://www.themeforest.net/user/pixinvent
==========================================================================================*/


$(document).ready(function(){
    i18next
        .use(window.i18nextBrowserLanguageDetector)        
        .init({
            debug: true,            
            nsSeparator: false,
            keySeparator: false,                   
            detection: {
                lookupQuerystring: 'lng',               
                order: ['querystring'],                
            },            
            lng: String.language,
            getAsync: false,
            fallbackLng:'es',// String.language,            
            resources: {
                en: {
                    translation: {
                        "common_info": "Information",
                        "footer_ProtegeteDelFraude": "Protect yourself from portal fraud",
                        "footer_EscogeUnIdioma": "Choose a language",
                        "footer_InformacionLegal": "Legal information",
                        "footer_DeclatacionDePrivacidad": "Privacy statement",
                        "footer_AvisoDeCookies": "Cookie notice",
                        "footer_ComunicateConNosotros": "Comunicate with us",
                        "modal_title_ProtegeteDelFraude": "Protect yourself from portal fraud",
                        "modal_title_InformacionLegal": "Legal information",
                        "modal_title_DeclaracionDePrivacidad": "Privacy statement",
                        "modal_title_AvisoDeCookies": "Cookie notice",
                        "modal_title_ComunicateConNosotros": "Comunicate with us",
                        "modal_title_TerminosDeServicio": "Usage Rules",
                        "login_userplaceholder": "User",
                        "login_passwordplaceholder": "Password",
                        "login_ingresar": "Enter",
                        "login_olvidastepassword": "Did you forget your password?",
                        "login_nuevousuario": "New user?",
                        "login_disclaimer_partOne": "Upon entering, you agree with the",
                        "login_disclaimer_partTwo": "and",
                        "login_disclaimer_TerminosDeServicio": "Usage Rules",
                        "login_disclaimer_DeclaracionPrivacidad": "Privacy statement",
                        "login_disclaimer_AvisoDeCookies": "Cookie notice",
                        "restaurarpassword_title": "Reset password",
                        "restaurarpassword_subtitle": "We will send a link to restore your password",
                        "restaurarpassword_email": "Email",
                        "restaurarpassword_btn": "Reset",
                        "registerUser_title": "Enter your personal identification",
                        "registerUser_subTitle": "Before you can access your account, you have to confirm your identity.",
                        "registerUser_nombres": "Names",
                        "registerUser_primernombre": "First Name",
                        "registerUser_segundonombre": "Second Name",
                        "registerUser_primerapellido": "First LastName",
                        "registerUser_segundoapellido": "Second LastName",
                        "registerUser_ssn": "Last 4 digits of SSN",
                        "registerUser_ssn_info": "Enter only the last 4 digits",
                        "registerUser_fechanacimiento": "Date of Birth",
                        "registerUser_email": "Email",
                        "registerUser_email_info": "The email will be your user to access your account",
                        "registerUser_password": "Password",
                        "registerUser_confirmpassword": "Confirm Password",
                        "registerUser_btn": "Register",
                        "registerUser_password_info_one": "The password must contain:",
                        "registerUser_password_info_two": "8 to 20, characters",
                        "registerUser_password_info_three": "Numbers",
                        "registerUser_password_info_four": "Special characters like",
                        "registerUser_zipcode": "ZipCode",
                        "registerUser_ConfirmPassword_validation": "Written passwords must match",
                        "registerUser_looksgood": "Looks good!",
                        "registerUser_name_validation": "Please provide a valid name.",
                        "registerUser_firtlastname_validation": "Please provide a valid first lastname.",
                        "registerUser_secondlastname_validation": "Please provide a valid second lastname.",
                        "registerUser_ssn_validation": "Please provide a valid SSN.",
                        "registerUser_zipcode_validation": "Please provide a valid ZipCode.",
                        "registerUser_email_validation": "Please provide a valid Email.",
                        "registerUser_email_info_title": "Consider:",
                        "registerUser_password_validation": "Please provide a valid Password.",
                        "registerUser_birthdate_validation": "Please provide a valid Date of Birth.",
                        "month": "Month",
                        "day": "Day",
                        "year": "Year",
                        "enero": "Janaury",
                        "febrero": "February",
                        "marzo": "March",
                        "abril": "April",
                        "mayo": "May",
                        "junio": "June",
                        "julio": "July",
                        "agosto": "August",
                        "setiembre": "Septembre",
                        "octubre": "October",
                        "noviembre": "November",
                        "diciembre": "December",
                        "common_warning": "Warning",
                        "common_unexpectedError": "An unexpected error has occurred",
                        "common_reloadTitel1": "Change Language",
                        "common_reloadSubTitle1": "When you change the language the saved data will be lost, do you want to continue?",
                        "common_reloadButtonOK": "Yes",
                        "common_reloadButtonCancel": "No",                      
                        "common_ButtonYes" : "Yes",
                        "common_ButtonNo": "No",
                        "common_ButtonEliminar": "Delete",
                        "common_ButtonBrowse": "Browse",
                        "common_File": "File",
                        "common_Confirm": "You will confirm the action",
                        "common_Sure": "Are you sure?",
                        "common_SureEnrollment": "Are you sure you want to change the insurer?",
                        "common_FileSelect": "Select a file.",
                        "common_FileType": "Only can choose files type",
                        "common_FileSize": "The size of the file wouldn´t be more than",
                        "DefaultIndex_Subtitle": "ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.",
                        "DefaultIndex_LearnMore": "Learn More",
                        "DefaultIndex_GettingStarted": "Getting Started",
                        "DefaultIndex_GettingStarted_subtitle": "ASP.NET Web API is a framework that makes it easy to build HTTP services that reach a broad range of clients, including browsers and mobile devices.ASP.NET Web API is an ideal platform for building RESTful applications on the.NET Framework.",
                        "DefaultIndex_GetMoreLibraries": "Get more libraries",
                        "DefaultIndex_GetMoreLibraries_subtitle": "NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.",
                        "DefaultIndex_WebHosting": "Web Hosting",
                        "DefaultIndex_WebHosting_subtitle": "You can easily find a web hosting company that offers the right mix of features and price for your applications.",
                        "DefaultIndex_GoDemo": "Go to Demo",
                        "CustomNavBar_Welcome_Text": "Welcome",
                        "CustomNavBar_CloseSesion_Text": "Close Session",
                        "Index_Search_Person": "Search Beneficiary",
                        "Index_Search_PMP": "Search PCP",
                        "Index_Conselor_Additional_Resources": "Counselor additional Resources",
                        "Index_Configuration": "Configuration",
                        "Index_Search_PCP/PCM": "Search PCP/PCM",
                        "Index_Reporting": "Reporting",
                        "SearchPerson_Tittle": "Search Beneficiary",
                        "SearchPerson_By_MPI": "By MPI",
                        "SearchPerson_By_Others": "By Others",
                        "SearchPerson_MPI": "MPI",
                        "SearchPerson_ContactName": "Contact Name",
                        "SearchPerson_MemberName": "Beneficiary Name",
                        "SearchPerson_ZipCode": "ZIP Code",
                        "SearchPerson_ApplicationNumber": "Application Number",
                        "SearchPerson_Search": "Search",
                        "ClenaPerson_Clean": "Clean",
                        "SearchPerson_SSN4": "SS (Last 4 digits)",
                        "SearchPerson_Birthday": "BirthDate",
                        "SearchPerson_Firstname": "First Name",
                        "SearchPerson_Last_Name": "Last Name",
                        "SearchPerson_Second_Last_Name": "Second Last Name",
                        "SearchPerson_Results": "Results",
                        "SearchPerson_Header_View": "View",
                        "SearchPerson_Header_Application_Number": "Application Number",
                        "SearchPerson_Header_Member_Name": "Beneficiary",
                        "SearchPerson_Header_Contact_Name": "Contact Name",
                        "SearchPerson_Validation_One": "Please Enter MPI",
                        "SearchPerson_Validation_Two": "The field SSN4 must be only 4 digits",
                        "SearchPerson_Validation_Three": "Minimum 2 of 5 fields are required.",
                        "Report_Validation_Fecha": "Date is requiered",
                        "Enrollment_MPI": "Beneficiary Name",
                        "Enrollment_TittleTab1": "Enrollment",
                        "Enrollment_TittleTab2": "Change History",
                        "Enrollment_TittleTab3": "Upload File",
                        "Enrollment_Tittle1": "General Data",
                        "Enrollment_Tittle2": "Select PCP/PMG",
                        "Enrollment_Tittle3": "PCP/PMG results under MCO selected",
                        "Enrollment_Tittle4": "Select one member above to display change history",                       
                        "Enrollment_Check": "Check",
                        "Enrollment_MemberName": "Member Name",
                        "Enrollment_Eligibility": "Eligibility",
                        "Enrollment_EffectiveDate": "Effective Date",
                        "Enrollment_CertificationDate": "Certification Date",
                        "Enrollment_ExpirationDate": "Expiration Date",
                        "Enrollment_CurrentMCO": "Current MCO",
                        "Enrollment_PCP/PMG": "PCP/PMG",
                        "Enrollment_Comment": "Comment",
                        "Enrollment_SelectNewMCO": "Select new MCO",
                        "Enrollment_SelectReasonJustCause": "Select Reason Just Cause.",
                        "Enrollment_InsertReasonJustCause": "Enter Reason Just Cause.",
                        "Enrollment_NotEnabledJustCause": "No es posibe realizar el cambio por justa causa ya que existe un cambio de MCO en proceso.",
                        "Enrollment_Message": "Message",
                        "Enrollment_McoDescription": "MCO Description",
                        "Enrollment_PMGDescription": "PMG Description",
                        "Enrollment_CPCP": "Current PCP:",
                        "Enrollment_CPMG": "Current PMG:",
                        "Enrollment_CMCO": "Current MCO:",
                        "Enrollment_PhisycianName": "Primary Care Physician Name (PCP):",
                        "Enrollment_Medical": "Primary Medical Group (PMG):",
                        "Enrollment_Datosact": "Current Insurer",
                        "Enrollment_Envcorreo": "Send to the mail:",
                        "Enrollment_Org": "Insurer (MCO):",
                        "Enrollment_Speciality": "Speciality",
                        "Enrollment_Municipality": "Town",
                        "Enrollment_ReasonJustCause": "Reason for just cause:",
                        "Enrollment_ReasonJustCauseCheck": "Change with Just Cause:",
                        "Enrollment_ReasonJustCause_Description": "Description:",
                        "Enrollment_NPI": "NPI",
                        "Direction": "Location",
                        "Enrollment_PcpCapacity": "PCP Capacity",
                        "Enrollment_BtnApplyPCP/PMG": "Apply PCP/PMG to selected member",
                        "Enrollment_ChangeSourceMco": "Change Source MCO",
                        "Enrollment_WhochangeMco": "Who change MCO",
                        "Enrollment_ChangeDateMco": "Change Date MCO",
                        "Enrollment_ChangeSourcePcp": "Change Source PCP",
                        "Enrollment_WhochangePcp": "Who change PCP",
                        "Enrollment_ChangeDatePcp": "Change Date PCP",
                        "Enrollment_User": "User",
                        "Enrollment_ChangeSource": "Source of Change",
                        "Enrollment_ChangeDate": "Date of Change",
                        "Report_MCO": "MCO Changes",
                        "Report_PMG": "PMG Changes",
                        "Report_PCP": "PCP Changes",
                        "Enrollment_MCO": "MCO",
                        "Enrollment_PMG": "PMG",
                        "Enrollment_PCP": "PCP",
                        "Enrollment_MCO_Old": "MCO Old",
                        "Enrollment_PMG_Old": "PMG Old",
                        "Enrollment_PCP_Old": "PCP Old",
                        "Enrollment_Validation_One": "Must be select at least one application",
                        "Enrollment_Validation_Two": "Must be select a same type of MCO",
                        "Enrollment_sucessfull_register": "The change was successful.",
                        "Enrollment_sucessfull_register_error_email": "The data was recorded successfully. Email could not be sent.", 
                        "Compare_Search": "SEARCH YOUR PROVIDER",
                        "Compare_SelectALL": "Select All",
                        "Compare_MCO": "Organitation of Manage Care",
                        "Compare_Ubication": "Ubication",
                        "Compare_Languaje": "Languaje",
                        "Compare_Spanish": "Spanish",
                        "Compare_English": "English",
                        "Compare_SearchFilter": "SEARCH FILTERS",
                        "Compare_Clear": "Clear",
                        "Compare_SearchResult": "SEARCH RESULT",
                        "Compare_Compare": "Compare",
                        "common_succesfull": "Successfull",
                        "common_succesfullEnrollment": "The change was successful.",
                        "common_success": "Success!",
                        "AllEnterText": "Enter text",
                        "EnterEmail": "Enter email",
                        "AllCboSelectAll": "All",
                        "SelectCboSelectSelect": "Select",
                        "AllBtnSearch": "Search",
                        "FullName": "Contact Name",
                        "Members": "Members",
                        "NoData": "No Data Found.",
                        "Menu_myprofile": "My Profile",
                        "Menu_configuration": "Settings",
                        "Menu_help": "Help",
                        "Menu_logout": "Logout",
                        "Menu_home": "Home",
                        "Person_settings_exportar_csv": "Export to Csv",
                        "Person_settings_setup_up_enrollment": "Set up Enrollment Period",
                        "datatable_no_data": "There is no data to show",
                        "datatable_previous": "Previous",
                        "datatable_first": "First",
                        "datatable_last": "Last",
                        "datatable_next": "Next",
                        "datatable_empty": "No data available in table",
                        "datatable_info": "Showing _START_ to _END_ of _TOTAL_ entries",
                        "datatable_LengthMenu": "Show _MENU_ entries",
                        "Enrollment_Seleccion":"Choose",
                        "Enrollment_btnDisplaySelection": "Change MCO",
                        "Enrollment_btnhideselection": "Cancel MCO Change",
                        "Person_export_History": "Export History",
                        "Person_export": "Export",
                        "Person_export_date_from": "Date From:",
                        "Person_export_date_to": "Date To:",
                        "Person_period_enrollment": "Period Enrollment",
                        "Person_period": "Period",
                        "Person_period_btn_save": "Save",
                        "Person_reports_web_applications": "Web Applications Report",
                        "Person_reports_system_downtime": "System Downtime Report",
                        "Person_reports_enrollment": "Enrollment Report",
                        "Person_reports_disenrollment": "Disenrollment Report",
                        "Person_reports_just_cause": "Just Cause Report",
                        "Person_reports_callcenter": "Call Center Report",
                        "Person_Filters": "Filters",
                        "Person_Filter": "Filter",
                        "Person_Date": "Date",
                        "Person_reports_date_from": "Date From:",
                        "Person_reports_date_to": "Date to:",
                        "Person_reports_web_public_hits": "TOTAL OF PUBLIC HITS",
                        "Person_reports_web_portal": "TOTAL lOGIN / SECURE PORTAL",
                        "Person_reports_web_search_requests": "TOTAL SEARCHES REQUESTED",
                        "Person_reports_web_number_email_register": "NUMBER OF EMAIL REGISTERED",
                        "Person_reports_enrollment_call_center": "Call Center Enrollments",
                        "Person_reports_enrollment_on_site": "On Site Enrollments",
                        "Person_reports_enrollment_web_site": "Website  Enrollments",
                        "Person_reports_disenrollment_call_center": "Call Center Disenrollments",
                        "Person_reports_disenrollment_on_site": "On Site Disenrollments",
                        "Person_reports_disenrollment_web_site": "Web Site Disenrollments",
                        "Navbar_searh_beneficiary": "Search Beneficiary",
                        "Navbar_searh_my_profile": "My Profile",
                        "Navbar_searh_setting": "Settings",
                        "Navbar_searh_report": "Reports",
                        "Navbar_searh_reject": "Rejected managment",
                        "Navbar_searh_searchpcp": "Search Provider",
                        "Navbar_searh_help": "Help",
                        "Navbar_searh_logout": "Logout",
                        "Enrollment_Pregunta": "Are you sure to continue with the change?",
                        "Navbar_welcome": "Welcome",
                        "Enrollment_Status": "Status",
                        "AllCboSelect": "Select one",
                        "EnrollmentApply": "Apply",
                        "Enrollment_CloseWindow": "Close",
                        "common_ExcessData": "Your search generated more than 200 providers. If you did not get the expected result, go to the previous page for a more specific search.",
                        "common_ExcessDataMember": "Your search generated more than 200 beneficiaries. If you did not get the expected result, do new specific search.",
                        "Email_Note": "A confirmation will be sent to your primary email.  Check the box if confirmation needs to be send to a secondary email.",
                        "Enrollment_EnvPhone": "Send Customer Satisfaction Survey:",
                        "EnterPhone": "Enter mobile phone",
                        "Phone_valid": "Please enter your mobile number to send the Customer Satisfaction Survey.  Otherwise, unmark the checkbox.",
                        "Phone_startCountryCode": "The phone number must not contain the country code.",
                        "Phone_lengthInvalid": "The phone number must be 10 digits.",
                        "Email_valid": "You must enter a valid email address.",
                        "common_alertMessage": "Our page is under maintenance. Please try again later.",
                        "common_alert": "Alert",
                        "Enrollment_MessageButtonSearch": "If the selected provider has more than one Specialty and/or PMG, select them and press the SEARCH button.",
                        "Enrollment_SelectAseguradora": "Choose Insurer (MCO)",
                        "PCP_Address": "Your provider accepts these insurers on the following locations.",
                        "PCP_Address_Select": "Select one of the following:",
                        "Select_your_provider_address": "Select the location for your Provider",
                        "Enrollment_Rejected": "Rejected",
                        "Enrollment_Processing": "In Process",
                        "Enrollment_Reject_Select": "Select",
                        "Enrollment_Change_Management": "Change Management",
                        "Enrollment_Reject_Select_Descripcion": "Update",
                        "Enrollment_Reject_Cancel": "Cancel",
                        "Enrollment_Reject_Cancel_Description": "Cancel"
                    }
                },
                es : {
                    translation: {
                        "common_info": "Informativo",
                        "footer_ProtegeteDelFraude": "Prot\u00e9gete del fraude en los portales",
                        "footer_EscogeUnIdioma": "Escoge un idioma",
                        "footer_InformacionLegal": "Informaci\u00f3n legal",
                        "footer_DeclatacionDePrivacidad": "Declaraci\u00f3n de privacidad",
                        "footer_AvisoDeCookies": "Aviso de cookies",
                        "footer_ComunicateConNosotros": "Comun\u00edcate con nosotros",
                        "modal_title_ProtegeteDelFraude": "Prot\u00e9gete del fraude en los portales",
                        "modal_title_InformacionLegal": "Informaci\u00f3n legal",
                        "modal_title_DeclaracionDePrivacidad": "Declaraci\u00f3n de privacidad",
                        "modal_title_AvisoDeCookies": "Aviso de cookies",
                        "modal_title_ComunicateConNosotros": "Comun\u00edcate con nosotros",
                        "modal_title_TerminosDeServicio": "Normas de Uso",
                        "login_userplaceholder": "Usuario",
                        "login_passwordplaceholder": "Contrase\u00f1a",
                        "login_ingresar": "Ingresar",
                        "login_olvidastepassword": "\u00BFOlvidaste tu Contrase\u00f1a?",
                        "login_nuevousuario": "\u00BFNuevo usuario?",
                        "login_disclaimer_partOne": "Al ingresar, est\u00e1s de acuerdo con los",
                        "login_disclaimer_partTwo": "y",
                        "login_disclaimer_TerminosDeServicio": "Normas de Uso",
                        "login_disclaimer_DeclaracionPrivacidad": "Declaraci\u00f3n de privacidad",
                        "login_disclaimer_AvisoDeCookies": "Aviso de cookies",
                        "restaurarpassword_title": "Restaurar Contrase\u00f1a",
                        "restaurarpassword_subtitle": "Enviaremos un enlace para restaurar su contrase\u00f1a",
                        "restaurarpassword_email": "Correo Electr\u00f3nico",
                        "restaurarpassword_btn": "Restaurar",
                        "registerUser_title": "Ingrese su identificaci\u00f3n personal",
                        "registerUser_subTitle": "Antes de que puedas acceder a su cuenta, tienes que confirmar su identidad.",
                        "registerUser_nombres": "Nombres",
                        "registerUser_primernombre": "Primer Nombre",
                        "registerUser_segundonombre": "Segundo Nombre",
                        "registerUser_primerapellido": "Primer Apellido",
                        "registerUser_segundoapellido": "Segundo Apellido",
                        "registerUser_ssn": "4 \u00faltimos d\u00edgitos del SSN",
                        "registerUser_ssn_info": "Ingresar solamente los \u00faltimos 4 d\u00edgitos",
                        "registerUser_fechanacimiento": "Fecha de Nacimiento",
                        "registerUser_email": "Correo Electr\u00f3nico",
                        "registerUser_email_info": "El correo electr\u00f3nico ser\u00e1 su usuario para acceder a su cuenta",
                        "registerUser_password": "Contrase\u00f1a",
                        "registerUser_confirmpassword": "Confirmar Contrase\u00f1a",
                        "registerUser_btn": "Registrar",
                        "registerUser_password_info_one": "La contrase\u00f1a debe contener:",
                        "registerUser_password_info_two": "8 a 20, caracteres",
                        "registerUser_password_info_three": "N\u00fameros",
                        "registerUser_password_info_four": "Caracteres especiales como",
                        "registerUser_zipcode": "C\u00f3digo postal",
                        "registerUser_ConfirmPassword_validation": "Las contrase\u00f1as escritas deben coincidir",
                        "registerUser_looksgood": "\u0020Se ve bien!",
                        "registerUser_name_validation": "Por favor escribe un nombre v\u00e1lido.",
                        "registerUser_firtlastname_validation": "Por favor escribe un primer apellido v\u00e1lido.",
                        "registerUser_secondlastname_validation": "Por favor escribe un segundo apellido v\u00e1lido.",
                        "registerUser_ssn_validation": "Por favor escribe un SSN v\u00e1lido.",
                        "registerUser_zipcode_validation": "Por favor escribe un C\u00f3digo Postal v\u00e1lido.",
                        "registerUser_email_validation": "Por favor escribe un Correo Electr\u00f3nico v\u00e1lido.",
                        "registerUser_email_info_title": "Tener en cuenta:",
                        "registerUser_password_validation": "Por favor escribe una Contrase\u00f1a v\u00e1lida.",
                        "registerUser_birthdate_validation": "Por favor escribe una Fecha de Nacimiento v\u00e1lida.",
                        "month": "Mes",
                        "day": "D\u00eda",
                        "year": "A\u00f1o",
                        "enero": "Enero",
                        "febrero": "Febrero",
                        "marzo": "Marzo",
                        "abril": "Abril",
                        "mayo": "Mayo",
                        "junio": "Junio",
                        "julio": "Julio",
                        "agosto": "Agosto",
                        "setiembre": "Setiembre",
                        "octubre": "Octubre",
                        "noviembre": "Noviembre",
                        "diciembre": "Diciembre",
                        "common_warning": "\u0020Advertencia",  
                        "common_unexpectedError": "Ocurri\u00f3 un error inesperado",                     
                        "common_reloadTitel1": "Cambiar idioma",
                        "common_reloadSubTitle1": "Al cambiar el idioma, se perder\u00e1 la informaci\u00f3n. \u00BF Desea continuar?",
                        "common_reloadButtonOK": "Si",
                        "common_reloadButtonCancel": "No",                        
                        "common_ButtonYes" : "Si",
                        "common_ButtonNo": "No",
                        "common_ButtonEliminar": "Eliminar",
                        "common_ButtonBrowse": "Buscar",
                        "common_File": "Archivo",
                        "common_Confirm": "Confirme la acci\u00f3n",
                        "common_Sure": "\u00BFEst\u00e1 seguro?",
                        "common_SureEnrollment": "\u00BFEst\u00E1 seguro que desea realizar el cambio de aseguradora?",
                        "common_FileSelect": "Seleccione un archivo.",
                        "common_FileType": "Solo puede seleccionar archivos de tipo",
                        "common_FileSize": "El tamaño del archivo no debe superar los",
                        "DefaultIndex_Subtitle": "ASP.NET es un framework web gratuito para crear excelentes sitios web y aplicaciones web utilizando HTML, CSS y JavaScript.",
                        "DefaultIndex_LearnMore": "Aprender m\u00E1s",
                        "DefaultIndex_GettingStarted": "Iniciando",
                        "DefaultIndex_GettingStarted_subtitle": "ASP.NET Web API es un marco que facilita la creaci\u00F3n de servicios HTTP que lleguen a una amplia gama de clientes, incluidos navegadores y dispositivos m\u00F3viles.ASP.NET Web API es una plataforma ideal para compilar aplicaciones RESTful en .NET Framework.",
                        "DefaultIndex_GetMoreLibraries": "Conseguir m\u00E1s librerias",
                        "DefaultIndex_GetMoreLibraries_subtitle": "NuGet es una extensi\u00F3n gratuita de Visual Studio que facilita agregar, eliminar y actualizar bibliotecas y herramientas en proyectos de Visual Studio.",
                        "DefaultIndex_WebHosting": "Alojamiento Web",
                        "DefaultIndex_WebHosting_subtitle": "Puede encontrar f\u00E1cilmente una empresa de alojamiento web que ofrezca la combinaci\u00F3n adecuada de caracteristicas y precio para sus aplicaciones.",
                        "DefaultIndex_GoDemo": "Ir al Demo",
                        "CustomNavBar_Welcome_Text": "Bienvenido",
                        "CustomNavBar_CloseSesion_Text": "Cerrar Sesi\u00f3n",
                        "Index_Search_Person": "Buscar Beneficiario",
                        "Index_Search_PMP": "Buscar Proveedor",
                        "Index_Conselor_Additional_Resources": "Recursos Adicionales del Consejero",
                        "Index_Configuration": "Configuraci\u00f3n",
                        "Index_Search_PCP/PCM": "Buscar PCP/PCM",
                        "Index_Reporting": "Reportes",
                        "SearchPerson_Tittle": "Buscar Beneficiario",
                        "SearchPerson_By_MPI": "Por MPI",
                        "SearchPerson_By_Others": "Por Otros",
                        "SearchPerson_MPI": "MPI",
                        "SearchPerson_ContactName": "Nombre de Contacto",
                        "SearchPerson_MemberName": "Nombre de Beneficiario",
                        "SearchPerson_ZipCode": "C\u00f3digo ZIP",
                        "SearchPerson_ApplicationNumber": "N\u00famero de Aplicaci\u00F3n",
                        "SearchPerson_Search": "Buscar",
                        "ClenaPerson_Clean": "Limpiar",
                        "SearchPerson_SSN4": "SS (\u00DAltimos 4 d\u00EDgitos)",
                        "SearchPerson_Birthday": "Fecha de Nacimiento",
                        "SearchPerson_Firstname": "Primer Nombre",
                        "SearchPerson_Last_Name": "Primer Apellido",
                        "SearchPerson_Second_Last_Name": "Segundo Apellido",
                        "SearchPerson_Results": "Resultados",
                        "SearchPerson_Header_View": "Ver",
                        "SearchPerson_Header_Application_Number": "N\u00famero de Aplicaci\u00f3n",
                        "SearchPerson_Header_Member_Name": "Beneficiario",
                        "SearchPerson_Header_Contact_Name": "Nombre de Contacto",
                        "SearchPerson_Validation_One": "Por favor ingrese MPI.",
                        "SearchPerson_Validation_Two": "El campo SSN4 debe tener solo 4 digitos",
                        "SearchPerson_Validation_Three": "Al menos 2 de los 5 campos son requeridos.",
                        "Report_Validation_Fecha": "Fecha es requerida",
                        "Enrollment_MPI": "Nombre del Beneficiario",
                        "Enrollment_TittleTab1": "Enrollment",
                        "Enrollment_TittleTab2": "Historial de Cambios",
                        "Enrollment_TittleTab3": "Subir Archivo",
                        "Enrollment_Tittle1": "Datos Generales",
                        "Enrollment_Tittle2": "Seleccionar PCP/PMG",
                        "Enrollment_Tittle3": "Resultados PCP/PMG bajo el MCO seleccionado",
                        "Enrollment_Tittle4": "Seleccionar uno de los miembros para mostrar el hist\u00f3rico de cambios",                       
                        "Enrollment_Check": "Seleccionar",
                        "Enrollment_MemberName": "Miembro",
                        "Enrollment_Eligibility": "Eligibilidad",
                        "Enrollment_EffectiveDate": "Fecha de Efectividad",
                        "Enrollment_CertificationDate": "Fecha de Certificaci\u00f3n",
                        "Enrollment_ExpirationDate": "Fecha de expiraci\u00f3n",
                        "Enrollment_CurrentMCO": "MCO Actual",
                        "Enrollment_Seleccion": "Elegir",
                        "Enrollment_PCP/PMG": "PCP/PMG",
                        "Enrollment_Comment": "Comentario",
                        "Enrollment_SelectNewMCO": "Seleccionar nuevo MCO",
                        "Enrollment_SelectReasonJustCause": "Seleccione raz\u00f3n justa causa.",
                        "Enrollment_InsertReasonJustCause": "Ingrese raz\u00f3n justa causa.",
                        "Enrollment_NotEnabledJustCause": "No es posibe realizar el cambio por justa causa ya que existe un cambio de MCO en proceso.",
                        "Enrollment_Message": "Mensaje",
                        "Enrollment_McoDescription": "Descripci\u00f3n del MCO",
                        "Enrollment_PMGDescription": "Descripci\u00f3n del PMG",
                        "Enrollment_CPCP": "PCP Actual:",
                        "Enrollment_CPMG": "PMG Actual:",
                        "Enrollment_CMCO": "MCO Actual:",
                        "Enrollment_PhisycianName": "Nombre del M\u00E9dico Primario (PCP):",
                        "Enrollment_Medical": "Grupo M\u00E9dico Primario (PMG):",
                        "Enrollment_Datosact": "Aseguradora actual",
                        "Enrollment_Actua": "Nueva aseguradora",
                        "Enrollment_Org": "Aseguradora (MCO):",
                        "Enrollment_Speciality": "Especialidad",
                        "Enrollment_Municipality": "Pueblo",
                        "Enrollment_ReasonJustCause": "Raz\u00f3n de cambio por justa causa:",
                        "Enrollment_ReasonJustCauseCheck": "Cambio por Justa Causa:",
                        "Enrollment_ReasonJustCause_Description": "Descripci\u00f3n:",
                        "Enrollment_NPI": "NPI",
                        "Direction": "Direcci\u00f3n",
                        "Enrollment_PcpCapacity": "Capacidad del PCP",
                        "Enrollment_BtnApplyPCP/PMG": "Aplicar PCP/PMG a los miembros seleccionados",
                        "Enrollment_ChangeSourceMco": "Medio del cambio MCO",
                        "Enrollment_WhochangeMco": "Qui\u00E9n cambi\u00f3 el MCO",
                        "Enrollment_ChangeDateMco": "Fecha del cambio MCO",
                        "Enrollment_ChangeSourcePcp": "Medio del cambio PCP",
                        "Enrollment_WhochangePcp": "Qui\u00E9n cambi\u00f3 el PCP",
                        "Enrollment_ChangeDatePcp": "Fecha del cambio PCP",
                        "Enrollment_User": "Usuario",
                        "Enrollment_ChangeSource": "Origen del Cambio",
                        "Enrollment_ChangeDate": "Fecha del Cambio",
                        "Report_MCO": "MCO Cambios",
                        "Report_PMG": "PMG Cambios",
                        "Report_PCP": "PCP Cambios",
                        "Enrollment_MCO": "MCO",
                        "Enrollment_PMG": "PMG",
                        "Enrollment_PCP": "PCP",
                        "Enrollment_Rejected": "Rechazado",
                        "Enrollment_MCO_Old": "MCO Anterior",
                        "Enrollment_PMG_Old": "PMG Anterior",
                        "Enrollment_PCP_Old": "PCP Anterior",
                        "AllEnterText": "Ingresar Texto",
                        "EnterEmail": "Ingrese su correo electr\u00f3nico",
                        "AllCboSelectAll": "Todos",
                        "SelectCboSelectSelect": "Seleccione",
                        "AllBtnSearch": "Buscar",
                        "Contact_FullName": "Nombre de Contacto",
                        "Members": "Miembros",                        
                        "Enrollment_Validation_One": "Debe seleccionar al menos una aplicaci\u00f3n",
                        "Enrollment_Validation_Two": "Debe seleccionar el mismo tipo de MCO",
                        "Enrollment_sucessfull_register": "Su cambio fue realizado exitosamente.",
                        "Enrollment_sucessfull_register_error_email": "El cambio fue registrado correctamente. No se pudo enviar el email",
                        "Compare_Search": "BUSQUE SU PROVEEDOR",
                        "Compare_SelectALL": "Seleccionar Todos",
                        "Compare_MCO": "Organizaci\u00f3n de Manejo de Cuidado",
                        "Compare_Ubication": "Ubicaci\u00f3n",
                        "Compare_Languaje": "Idioma",
                        "Compare_Spanish": "Espa\u00f1ol",
                        "Compare_English": "Ingl\u00E9s",
                        "Compare_SearchFilter": "FILTROS DE B\u00daSQUEDA",
                        "Compare_Clear": "Limpiar",
                        "Compare_SearchResult": "RESULTADO DE B\u00daSQUEDA",
                        "Compare_Compare": "Comparar",
                        "common_succesfull": "\u00c9xito",
                        "common_succesfullEnrollment": "Su cambio fue realizado exitosamente.",
                        "common_success": "\u00c9xito!",
                        "NoData": "No se encontraron datos.",
                        "Menu_myprofile": "Mi Perfil",
                        "Menu_configuration": "Configuraci\u00f3n",
                        "Menu_help": "Ayuda",
                        "Menu_logout": "Cerrar Sesi\u00f3n",
                        "Menu_home": "Inicio",
                        "Person_settings_exportar_csv": "Exportar a Csv",
                        "Person_settings_setup_up_enrollment": "Configurar Periodo de Inscripci\u00f3n",
                        "datatable_no_data": "No existe data para mostrar",
                        "datatable_previous": "Anterior",
                        "datatable_first": "Primero",
                        "datatable_last": "\u00daltimo",
                        "datatable_next": "Siguiente",
                        "datatable_empty": "Ning\u00fan dato disponible en esta tabla",
                        "datatable_info": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "datatable_LengthMenu": "Mostrar _MENU_ registros",
                        "Enrollment_btnDisplaySelection": "Realizar cambio de MCO",
                        "Enrollment_btnhideselection": "Cancelar cambio de MCO",
                        "Person_export_History": "Exportar Historial",
                        "Person_export": "Exportar",
                        "Person_export_date_from": "Fecha Desde:",
                        "Person_export_date_to": "Fecha Hasta:",
                        "Person_period_enrollment": "Periodo de Inscripci\u00f3n",
                        "Person_period": "Periodo",
                        "Person_period_btn_save":"Guardar",
                        "Person_reports_web_applications": "Informe de aplicaciones web",
                        "Person_reports_system_downtime": "Informe de tiempo de inactividad del sistema",
                        "Person_reports_enrollment": "Informe de inscripci\u00f3n",
                        "Person_reports_disenrollment": "Informe de cancelaci\u00f3n de inscripci\u00f3n",
                        "Person_reports_just_cause": "Informe de justa causa",
                        "Person_reports_callcenter": "Informe de Call Center",
                        "Person_Filters": "Filtros",
                        "Person_Filter": "Filtrar",
                        "Person_Date":"Fecha",
                        "Person_reports_date_from": "Fecha desde:",
                        "Person_reports_date_to": "Fecha hasta:",
                        "Person_reports_web_public_hits": "TOTAL DE INGRESOS P\u00daBLICOS (SELFSERVICES)",
                        "Person_reports_web_portal": "INICIO TOTAL / PORTAL SEGURO",
                        "Person_reports_web_search_requests": "TOTAL B\u00daSQUEDAS SOLICITADAS",
                        "Person_reports_web_number_email_register": "TOTAL DE INGRESOS INTERNOS (ASIST)",
                        "Person_reports_enrollment_call_center": "Inscripciones por Centro de Llamadas",
                        "Person_reports_enrollment_on_site": "Inscripciones en sitio",
                        "Person_reports_enrollment_web_site": "Inscripciones por Internet",
                        "Person_reports_disenrollment_call_center": "Cancelaciones de inscripciones por Centro de Llamadas",
                        "Person_reports_disenrollment_on_site": "Cancelaciones de inscripciones en sitio",
                        "Person_reports_disenrollment_web_site": "Cancelaciones de inscripciones por Internet",
                        "Navbar_searh_beneficiary": "Buscar Beneficiario",
                        "Navbar_searh_my_profile": "Mi Perfil",
                        "Navbar_searh_setting": "Configuraci\u00f3n",
                        "Navbar_searh_report": "Reportes",
                        "Navbar_searh_reject": "Gesti\u00f3n de Rechazos",
                        "Navbar_searh_searchpcp": "Buscar Proveedor",
                        "Navbar_searh_help": "Ayuda",
                        "Navbar_searh_logout": "Cerrar Sesi\u00f3n",
                        "Enrollment_Pregunta": "\u00BFEst\u00e1 seguro de realizar el siguiente cambio?",
                        "Enrollment_Envcorreo": "Enviar al correo electr\u00f3nico:",
                        "Navbar_welcome": "Bienvenid@@",
                        "Enrollment_Status": "Estatus",
                        "AllCboSelect": "Seleccione",
                        "EnrollmentApply": "Aplicar",
                        "Enrollment_CloseWindow": "Cerrar",
                        "common_ExcessData": "Su b\u00fasqueda gener\u00f3 m\u00e1s de 200 proveedores. Si no obtuvo el resultado esperado, regrese a la p\u00e1gina anterior para una b\u00fasqueda m\u00e1s espec\u00edfica.",
                        "common_ExcessDataMember": "Su b\u00fasqueda gener\u00f3 m\u00e1s de 200 beneficiarios. Si no obtuvo el resultado esperado, realice una b\u00fasqueda m\u00e1s espec\u00edfica.",
                        "Email_Note": "La confirmaci\u00f3n del cambio realizado ser\u00E1 enviada a su direcci\u00f3n de correo electr\u00f3nico principal. Si desea, puede a\u00F1adir una direcci\u00f3n de correo alterna marcando el siguiente encasillado.",
                        "Enrollment_EnvPhone": "Enviar encuesta de satisfacci\u00f3n:",
                        "EnterPhone": "Ingrese su n\u00famero celular",
                        "Phone_valid": "Debe ingresar su n\u00FAmero celular para enviar la encuesta. De lo contrario, elimine la selecci\u00f3n del encasillado.",
                        "Phone_startCountryCode": "El n\u00FAmero de tel\u00e9fono no debe contener el c\u00f3digo de pa\u00eds.",
                        "Phone_lengthInvalid": "El n\u00FAmero de tel\u00e9fono debe ser de 10 d\u00edgitos.",
                        "Email_valid": "Debe escribir la direcci\u00f3n de correo electr\u00f3nico correctamente.",
                        "common_alertMessage": "En este momento nuestra p\u00E1gina se encuentra en mantenimiento. Por favor intente m\u00E1s tarde.",
                        "common_alert": "Aviso",
                        "Enrollment_MessageButtonSearch": "Si el proveedor seleccionado tiene m\u00E1s de una Especialidad y/o PMG, seleccione los mismos y presione el bot\u00F3n BUSCAR.",
                        "Enrollment_SelectAseguradora": "Seleccione Aseguradora",
                        "PCP_Address": "Su m\u00e9dico en la direcci\u00f3n seleccionada acepta las siguientes aseguradoras.",
                        "PCP_Address_Select": "Seleccione una de las siguientes:",
                        "Select_your_provider_address": "Seleccione la direcci\u00f3n de su Proveedor",
                        "Enrollment_Processing": "En Proceso",
                        "Enrollment_Reject_Select": "Seleccione",
                        "Enrollment_Change_Management": "Gesti\u00f3n de Cambios",
                        "Enrollment_Reject_Select_Descripcion": "Modificar",
                        "Enrollment_Reject_Cancel": "Cancelar",
                        "Enrollment_Reject_Cancel_Description": "Cancelar"
                    }
                }
            },
            returnObjects: true
        },        
        function (err, t) {
            // resources have been loaded
            jqueryI18next.init(i18next, $);

            $('#mainCreateApplication').localize();          

            if(i18next.language == 'en'){
                $('.lng-nav li a').removeClass('active');
                $('.lng-nav li a[data-lng="en"]').addClass('active');

                $('.lng-dropdown a').removeClass('active');
                var drop_lng = $('.lng-dropdown a[data-lng="en"]').addClass('active');
                $('#dropdown-active-item').html(drop_lng.html());
            }

            if(i18next.language == 'es'){
                $('.lng-nav li a').removeClass('active');
                $('.lng-nav li a[data-lng="es"]').addClass('active');

                $('.lng-dropdown a').removeClass('active');
                var drop_lng = $('.lng-dropdown a[data-lng="es"]').addClass('active');
                $('#dropdown-active-item').html(drop_lng.html());
            }
           
        });
    i18next.on('languageChanged', function (lng) {

        // resources have been loaded
        jqueryI18next.init(i18next, $);

        $('#mainCreateApplication').localize();      

        //HTM INICIO
        // Cambio de idioma en el login
        $('.main-body').localize();
        $('.customCardLogin').localize();   
        //HTM FIN

        if (i18next.language == 'en') {
            $('.lng-nav li a').removeClass('active');
            $('.lng-nav li a[data-lng="en"]').addClass('active');

            $('.lng-dropdown a').removeClass('active');
            var drop_lng = $('.lng-dropdown a[data-lng="en"]').addClass('active');
            $('#dropdown-active-item').html(drop_lng.html());
        }

        if (i18next.language == 'es') {
            $('.lng-nav li a').removeClass('active');
            $('.lng-nav li a[data-lng="es"]').addClass('active');

            $('.lng-dropdown a').removeClass('active');
            var drop_lng = $('.lng-dropdown a[data-lng="es"]').addClass('active');
            $('#dropdown-active-item').html(drop_lng.html());
        }
        
    });     
});