--DECLARE      
-- @ProcessHeaderId INT = 119,
-- @ProcessType VARCHAR(20) = 'GetDataForAses'      
CREATE PROCEDURE [ExportAses].[USP_GetDataForAses]         
 @ProcessHeaderId INT,  
 @ProcessType VARCHAR(20)  
AS        
BEGIN  
 DECLARE @Procedure VARCHAR(100)      
 DECLARE @Rows int      
 DECLARE @Error VARCHAR(300)  
       
 DECLARE @TransactionName VARCHAR(50) = 'PROCESS_TRANSACTION_GETDATA_FOR_ASES'      
      
 BEGIN TRY      
  SET @Procedure = OBJECT_NAME(@@PROCID)  
      
  BEGIN TRAN @TransactionName   
  --Borrando tablas temporales        
 IF OBJECT_ID('tempdb..#Temp') IS NOT NULL        
 BEGIN        
  DROP TABLE #Temp;        
 END;      
  
 CREATE TABLE #Temp(        
   [Row] [nvarchar](max) NULL  
   )  
  
 INSERT INTO #Temp  
 SELECT CONCAT(      
 RIGHT(replicate(' ', 30)+ISNULL(RECORD_TYPE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'RECORD_TYPE')),      
 RIGHT(replicate(' ', 30)+ISNULL(TRAN_ID,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'TRAN_ID')),      
 RIGHT(replicate(' ', 30)+ISNULL(PROCESS_DATE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PROCESS_DATE')),      
 RIGHT(replicate(' ', 30)+ISNULL(REGION,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'REGION')),      
 RIGHT(replicate(' ', 30)+ISNULL(CARRIER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'CARRIER')),      
 RIGHT(replicate(' ', 30)+ISNULL(MEMBER_PRIMARY_CENTER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'MEMBER_PRIMARY_CENTER')),      
 RIGHT(replicate(' ', 30)+ISNULL(ODSI_FAMILY_ID,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ODSI_FAMILY_ID')),      
 RIGHT(replicate(' ', 30)+ISNULL(MEMBER_SSN,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'MEMBER_SSN')),      
 RIGHT(replicate(' ', 30)+ISNULL(MEMBER_SUFFIX,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'MEMBER_SUFFIX')),      
 RIGHT(replicate(' ', 30)+ISNULL(EFFECTIVE_DATE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'EFFECTIVE_DATE')),      
 RIGHT(replicate(' ', 30)+ISNULL(PLAN_TYPE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PLAN_TYPE')),      
 RIGHT(replicate(' ', 30)+ISNULL(PLAN_VERSION,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PLAN_VERSION')),      
 RIGHT(replicate(' ', 30)+ISNULL(MPI,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'MPI')),      
 LEFT(ISNULL(PCP1,'')+replicate(' ', 30),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PCP1')),      
 RIGHT(replicate(' ', 30)+ISNULL(PCP1_EFFECTIVE_DATE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PCP1_EFFECTIVE_DATE')),      
 RIGHT(replicate(' ', 30)+ISNULL(PCP2,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PCP2')),      
 RIGHT(replicate(' ', 30)+ISNULL(PCP2_EFFECTIVE_DATE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PCP2_EFFECTIVE_DATE')),      
 RIGHT(replicate(' ', 30)+ISNULL(FAMILY_PRIMARY_CENTER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'FAMILY_PRIMARY_CENTER')),      
 RIGHT(replicate(' ', 30)+ISNULL(PMG_TAX_ID_EFF_DT,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PMG_TAX_ID_EFF_DT')),      
 RIGHT(replicate(' ', 30)+ISNULL(IPA_PCP_CHANGE_REASON,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'IPA_PCP_CHANGE_REASON')),      
 RIGHT(replicate(' ', 30)+ISNULL(MEDICARE_INDICATOR,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'MEDICARE_INDICATOR')),      
 RIGHT(replicate(' ', 30)+ISNULL(HIC_NUMBER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'HIC_NUMBER')),      
 RIGHT(replicate(' ', 30)+ISNULL(REJECT_IDENTIFIER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'REJECT_IDENTIFIER')),      
 RIGHT(replicate(' ', 30)+ISNULL(RECORD_KEY,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'RECORD_KEY')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_1,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_1')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_2,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_2')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_3,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_3')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_4,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_4')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_5,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_5')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_6,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_6')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_7,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_7')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_8,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_8')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_9,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_9')),      
 RIGHT(replicate(' ', 30)+ISNULL(ERROR_CODE_10,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'ERROR_CODE_10')),      
 RIGHT(replicate(' ', 30)+ISNULL(UPDATE_DATE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'UPDATE_DATE')),      
 RIGHT(replicate(' ', 30)+ISNULL(UPDATE_USER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'UPDATE_USER')),      
 RIGHT(replicate(' ', 30)+ISNULL(IPA_ESPECIAL,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'IPA_ESPECIAL')),      
 RIGHT(replicate(' ', 30)+ISNULL(CONTRACT_NUMBER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'CONTRACT_NUMBER')),      
 RIGHT(replicate(' ', 30)+ISNULL(SPECIAL_ENROLL,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'SPECIAL_ENROLL')),      
 RIGHT(replicate(' ', 30)+ISNULL(PMG_TAX_ID,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'PMG_TAX_ID')),      
 RIGHT(replicate(' ', 30)+ISNULL(DATA_SOURCE,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'DATA_SOURCE')),      
 RIGHT(replicate(' ', 30)+ISNULL(FILLER,''),(SELECT CAST(CHARACTER_MAXIMUM_LENGTH AS INT) FROM  INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ExportFileForAses' AND COLUMN_NAME = 'FILLER'))      
 ) AS RowSus      
   FROM [ExportAses].[ExportFileForAses]      
   WHERE      
  [PROCESS_HEADER_ID] = @ProcessHeaderId      
  
INSERT INTO #Temp 
SELECT
CONCAT(
	'TRAILER',
	replicate(' ', 10),
	RIGHT(replicate('0', 8) + (SELECT CAST(COUNT(*) AS VARCHAR) FROM #Temp), 8),
	replicate(' ', 10),
	'230',
	replicate(' ', 191)
)
  
 ----UPDATE ENROLLMENTHISTORIE  
 --UPDATE EH SET EH.StatusId=2  
 --FROM [Enrollment].[EnrollmentHistories] EH (NOLOCK)  
 --INNER JOIN [Enrollment].[Members] M (NOLOCK) ON M.ID= EH.MemberId   
 --INNER JOIN [Enrollment].[Families] F (NOLOCK) ON EH.FamilyId = F.Id   
 --INNER JOIN [Enrollment].[ManagedCareOrganizations] MCO (NOLOCK) ON EH.MCOId = MCO.Id  
 --INNER JOIN [Enrollment].[PersonPrimaryCarePhysician] PCP (NOLOCK) ON EH.PCPId = PCP.Id  
 --INNER JOIN [Enrollment].[PrimaryMedicalGroup] PMG (NOLOCK) ON EH.PMGId = PMG.Id  
 --WHERE EH.StatusId=1  

 --UPDATE [Enrollment].[EnrollmentHistories]      
 --SET      
 -- StatusId = 2    
 --WHERE      
 -- [Id] IN (SELECT MEMBER_ID_ENROLLMENTHISTORY FROM [ExportAses].[ExportFileForAses] WHERE PROCESS_HEADER_ID = @ProcessHeaderId) 
      
 UPDATE [ExportAses].[ExportFileForAses]      
 SET      
  GENERATED_FOR_ASES = 1,      
  GENERATED_FOR_ASES_DATE = GETDATE(),
  StatusId = 2      
 WHERE      
  [PROCESS_HEADER_ID] = @ProcessHeaderId      
  
  SET @Rows = @@ROWCOUNT      
  SET @Error = @@ERROR       
      
  COMMIT TRAN @TransactionName      
      
  SELECT      
  CAST(@ProcessHeaderId as varchar(10)) As ProcessHeaderId  
  ,(SELECT [Row] FROM #Temp FOR JSON AUTO) AS Rows    
  ,@ProcessType AS ProcessType      
  ,@Error AS ErrorNumber      
  ,@Procedure AS ProcedureName      
  ,NULL AS ErrorLine      
  ,CAST(@Rows as varchar(10)) + ' Affected Rows' AS ProcessMessage      
  
 END TRY  
 BEGIN CATCH      
  ROLLBACK TRAN @TransactionName      
  SELECT      
   NULL As ProcessHeaderId  
  ,NULL AS Rows      
  ,@ProcessType AS ProcessType      
  ,ERROR_NUMBER() AS ErrorNumber      
  ,ERROR_PROCEDURE() AS ProcedureName      
  ,ERROR_LINE() AS ErrorLine      
  ,ERROR_MESSAGE() AS ProcessMessage      
 END CATCH     
END