//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSurvey.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnrollmentSurvey.Idioma.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string ases_Advertencia {
            get {
                return ResourceManager.GetString("ases_Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página no encontrada..
        /// </summary>
        public static string ases_not_found {
            get {
                return ResourceManager.GetString("ases_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Encuesta.
        /// </summary>
        public static string txt_btn_enviar_encuesta {
            get {
                return ResourceManager.GetString("txt_btn_enviar_encuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por completar esta encuesta.
        /// </summary>
        public static string txt_btn_gracias {
            get {
                return ResourceManager.GetString("txt_btn_gracias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string txt_btn_idioma {
            get {
                return ResourceManager.GetString("txt_btn_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta encuesta ya ha sido completada..
        /// </summary>
        public static string txt_encuesta_completa {
            get {
                return ResourceManager.GetString("txt_encuesta_completa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En una escala del 1 al 10, por favor indique cómo fue su experiencia para el cambio de asegurado en el portal Web.
        /// </summary>
        public static string txt_encuesta_recomendacion {
            get {
                return ResourceManager.GetString("txt_encuesta_recomendacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta de Satisfacción de Servicio.
        /// </summary>
        public static string txt_encuesta_satisfaccion {
            get {
                return ResourceManager.GetString("txt_encuesta_satisfaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija Si o No para poder continuar..
        /// </summary>
        public static string txt_error_barra {
            get {
                return ResourceManager.GetString("txt_error_barra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le recordamos que debe seleccionar una opción..
        /// </summary>
        public static string txt_error_sino {
            get {
                return ResourceManager.GetString("txt_error_sino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string txt_Salir {
            get {
                return ResourceManager.GetString("txt_Salir", resourceCulture);
            }
        }
    }
}
