CREATE TABLE [ExportAses].[FamilyRecords] (
    [TranId]                       NCHAR (10)     COLLATE Modern_Spanish_CI_AS NULL,
    [ProcessDate]                  NCHAR (8)      COLLATE Modern_Spanish_CI_AS NULL,
    [FamilySSN]                    NCHAR (10)     COLLATE Modern_Spanish_CI_AS NULL,
    [FamilySuffix]                 NCHAR (10)     COLLATE Modern_Spanish_CI_AS NULL,
    [FamilyId]                     NVARCHAR (11)  COLLATE Modern_Spanish_CI_AS NULL,
    [ContactLastName1]             NVARCHAR (15)  COLLATE Modern_Spanish_CI_AS NULL,
    [ContactLastName2]             NVARCHAR (15)  COLLATE Modern_Spanish_CI_AS NULL,
    [ContactFirstName]             NVARCHAR (20)  COLLATE Modern_Spanish_CI_AS NULL,
    [Region]                       NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [Municipality]                 NVARCHAR (4)   COLLATE Modern_Spanish_CI_AS NULL,
    [Facility]                     NVARCHAR (4)   COLLATE Modern_Spanish_CI_AS NULL,
    [InvestigationInd]             NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [TransactionType]              NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [EffectiveDate]                NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [FinancialRespPct]             NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [CertifierNumber]              NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [ExpirationDate]               NVARCHAR (8)   COLLATE Modern_Spanish_CI_AS NULL,
    [CondEligInd]                  NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [MailingAddress1]              NVARCHAR (25)  COLLATE Modern_Spanish_CI_AS NULL,
    [MailingAddress2]              NVARCHAR (25)  COLLATE Modern_Spanish_CI_AS NULL,
    [MailingCity]                  NVARCHAR (16)  COLLATE Modern_Spanish_CI_AS NULL,
    [MailingZip]                   NVARCHAR (5)   COLLATE Modern_Spanish_CI_AS NULL,
    [MalingZip4]                   NCHAR (4)      COLLATE Modern_Spanish_CI_AS NULL,
    [ResidenceAddress1]            NVARCHAR (25)  COLLATE Modern_Spanish_CI_AS NULL,
    [ResidenceAddress2]            NVARCHAR (25)  COLLATE Modern_Spanish_CI_AS NULL,
    [ResidenceCity]                NVARCHAR (16)  COLLATE Modern_Spanish_CI_AS NULL,
    [ResidenceZip]                 NVARCHAR (5)   COLLATE Modern_Spanish_CI_AS NULL,
    [ResidenceZip4]                NVARCHAR (4)   COLLATE Modern_Spanish_CI_AS NULL,
    [Phone]                        NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [OtherInsurer1]                NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [OtherPolicy1]                 NVARCHAR (20)  COLLATE Modern_Spanish_CI_AS NULL,
    [OtherInsurer2]                NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [OtherPolicy2]                 NVARCHAR (20)  COLLATE Modern_Spanish_CI_AS NULL,
    [OtherInsurer3]                NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [OtherPolicy3]                 NVARCHAR (20)  COLLATE Modern_Spanish_CI_AS NULL,
    [Members]                      NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [OdsiMembersElegible]          NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [UserCode]                     NVARCHAR (6)   COLLATE Modern_Spanish_CI_AS NULL,
    [EntryDate]                    NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [PctofPovertylevel]            NVARCHAR (3)   COLLATE Modern_Spanish_CI_AS NULL,
    [DeductibleLevelCode]          NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [HCREMembersElegible]          NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [HCREDenialCode]               NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [CarrierCode]                  NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [EffectiveCarrierDate]         NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [ElaErrors]                    NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [Mancomunado]                  NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [PmgTaxId]                     NVARCHAR (9)   COLLATE Modern_Spanish_CI_AS NULL,
    [NewCarrier]                   NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [NewPMGTaxId]                  NVARCHAR (9)   COLLATE Modern_Spanish_CI_AS NULL,
    [NewPMGEffectiveDate]          NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [ContractNumber]               NVARCHAR (13)  COLLATE Modern_Spanish_CI_AS NULL,
    [RegionASES]                   NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [NewCarrierEffectiveDate]      NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [PMGEffectiveDate]             NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [CertificationDate]            NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [PrimaryCenterPCPChangeReason] NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [AutoEnrollIndicator]          NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [AutoEnrollDate]               NVARCHAR (8)   COLLATE Modern_Spanish_CI_AS NULL,
    [PamNewFamilyId]               NVARCHAR (11)  COLLATE Modern_Spanish_CI_AS NULL,
    [ApplicationNumber]            NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [MedicaidCancelationDt]        NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [RegionMoveEffDt]              NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [RateCell]                     NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [Gender]                       NVARCHAR (2)   COLLATE Modern_Spanish_CI_AS NULL,
    [NewCardIdDate]                NVARCHAR (10)  COLLATE Modern_Spanish_CI_AS NULL,
    [BlockNumber]                  NCHAR (6)      COLLATE Modern_Spanish_CI_AS NULL,
    [ProcessHeaderId]              INT            NULL,
    [IsValidForImport]             BIT            NULL,
    [MessageInvalid]               NVARCHAR (MAX) COLLATE Modern_Spanish_CI_AS NULL,
    CONSTRAINT [FK_FamilyRecords_ProcessHeader] FOREIGN KEY ([ProcessHeaderId]) REFERENCES [ExportAses].[ProcessHeader] ([ID])
);







