CREATE TABLE [ExportAses].[ImportRejectfileFromAses] (
    [RECORD_TYPE]                 NCHAR (2)     NULL,
    [TRAN_ID]                     NCHAR (2)     NULL,
    [PROCESS_DATE]                NCHAR (16)    NULL,
    [REGION]                      NCHAR (2)     NULL,
    [CARRIER]                     NCHAR (4)     NULL,
    [MEMBER_PRIMARY_CENTER]       NCHAR (8)     NULL,
    [ODSI_FAMILY_ID]              NCHAR (22)    NULL,
    [MEMBER_SSN]                  NCHAR (18)    NULL,
    [MEMBER_SUFFIX]               NCHAR (4)     NULL,
    [EFFECTIVE_DATE]              NCHAR (16)    NULL,
    [PLAN_TYPE]                   NCHAR (4)     NULL,
    [PLAN_VERSION]                NCHAR (6)     NULL,
    [MPI]                         NCHAR (26)    NULL,
    [PCP1]                        NCHAR (30)    NULL,
    [PCP1_EFFECTIVE_DATE]         NCHAR (16)    NULL,
    [PCP2]                        NCHAR (30)    NULL,
    [PCP2_EFFECTIVE_DATE]         NCHAR (16)    NULL,
    [FAMILY_PRIMARY_CENTER]       NCHAR (8)     NULL,
    [PMG_TAX_ID_EFF_DT]           NCHAR (16)    NULL,
    [IPA_PCP_CHANGE_REASON]       NVARCHAR (4)  NULL,
    [MEDICARE_INDICATOR]          NVARCHAR (2)  NULL,
    [HIC_NUMBER]                  NVARCHAR (24) NULL,
    [REJECT_IDENTIFIER]           NVARCHAR (2)  NULL,
    [RECORD_KEY]                  NVARCHAR (28) NULL,
    [ERROR_CODE_1]                NVARCHAR (6)  NULL,
    [ERROR_CODE_2]                NVARCHAR (6)  NULL,
    [ERROR_CODE_3]                NVARCHAR (6)  NULL,
    [ERROR_CODE_4]                NVARCHAR (6)  NULL,
    [ERROR_CODE_5]                NVARCHAR (6)  NULL,
    [ERROR_CODE_6]                NVARCHAR (6)  NULL,
    [ERROR_CODE_7]                NVARCHAR (6)  NULL,
    [ERROR_CODE_8]                NVARCHAR (6)  NULL,
    [ERROR_CODE_9]                NVARCHAR (6)  NULL,
    [ERROR_CODE_10]               NVARCHAR (6)  NULL,
    [UPDATE_DATE]                 NVARCHAR (16) NULL,
    [UPDATE_USER]                 NVARCHAR (16) NULL,
    [IPA_ESPECIAL]                NVARCHAR (2)  NULL,
    [CONTRACT_NUMBER]             NCHAR (26)    NULL,
    [SPECIAL_ENROLL]              NVARCHAR (6)  NULL,
    [PMG_TAX_ID]                  NCHAR (18)    NULL,
    [DATA_SOURCE]                 NCHAR (4)     NULL,
    [FILLER]                      NCHAR (8)     NULL,
    [BLOCK_NUMBER]                NCHAR (20)    NULL,
    [PROCESS_HEADER_ID]           INT           NULL,
    [GENERATED_FOR_ASES]          BIT           NULL,
    [GENERATED_FOR_ASES_DATE]     DATE          NULL,
    [REJECTED_FROM_ASES]          BIT           NULL,
    [REJECTED_FROM_ASES_DATE]     DATE          NULL,
    [MEMBER_ID_ENROLLMENTHISTORY] INT           NULL,
    [STATUSID]                    INT           NULL
);

