//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMcoConnector_V1")]
public interface IMcoConnector_V1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetApplicationPeopleByMpi", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetApplicationPeopleByMpiResponse")]
    Mediti2.McoConnector.AppPersonSearchResult_V1 GetApplicationPeopleByMpi(string mpi);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetApplicationPeopleByPersonID", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetApplicationPeopleByPersonIDResponse")]
    Mediti2.McoConnector.AppPersonSearchResult_V1 GetApplicationPeopleByPersonID(int personID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetApplicationPeopleByName", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetApplicationPeopleByNameResponse")]
    Mediti2.McoConnector.AppPersonSearchResult_V1 GetApplicationPeopleByName(string firstName, string lastName1, string lastName2, string ssnLast4, System.DateTime dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetMediti2AppMembers", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetMediti2AppMembersResponse")]
    Mediti2.McoConnector.AppMemberInfo_V1 GetMediti2AppMembers(int applicationMemberID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetPeople2", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetPeople2Response")]
    Mediti2.McoConnector.AppPerson_V1[] GetPeople2(string mpi, System.Nullable<int> personID, string firstName, string lastName1, string lastName2, string ssnLast4, System.Nullable<System.DateTime> dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetSpecialties", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetSpecialtiesResponse")]
    Mediti2.McoConnector.PcpSpecialty_V1[] GetSpecialties();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetEnrollmentChangeHistory", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetEnrollmentChangeHistoryResponse")]
    Mediti2.McoConnector.EnrollmentHistory_V1[] GetEnrollmentChangeHistory(int personID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetMcos", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetMcosResponse")]
    Mediti2.McoConnector.Mco_V1[] GetMcos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetMcosWithCapacity", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetMcosWithCapacityResponse")]
    Mediti2.McoConnector.SimpleEntity_V1[] GetMcosWithCapacity();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetApplicationPeople", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetApplicationPeopleResponse")]
    Mediti2.McoConnector.PersonMcoDisplay_V1[] GetApplicationPeople(string applicationNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetPerson", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetPersonResponse")]
    Mediti2.McoConnector.PersonMcoDisplay_V1 GetPerson(string mpi);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetPeople", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetPeopleResponse")]
    Mediti2.McoConnector.PersonMcoDisplay_V1[] GetPeople(string firstName, string lastName1, string lastName2, string ssnLast4, System.DateTime dateOfBirth);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/SetPersonMco", ReplyAction="http://tempuri.org/IMcoConnector_V1/SetPersonMcoResponse")]
    Mediti2.McoConnector.PersonMcoDisplay_V1 SetPersonMco(Mediti2.McoConnector.PersonMco_V1 value, string user, Mediti2.McoConnector.DataSource_V1 source);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/SetRandomMco", ReplyAction="http://tempuri.org/IMcoConnector_V1/SetRandomMcoResponse")]
    Mediti2.McoConnector.PersonMcoDisplay_V1 SetRandomMco(int personID, string user, Mediti2.McoConnector.DataSource_V1 source);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetPrimaryCarePhysicians", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetPrimaryCarePhysiciansResponse")]
    Mediti2.McoConnector.PcpPmg_V1[] GetPrimaryCarePhysicians();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetPMGs", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetPMGsResponse")]
    Mediti2.McoConnector.Pmg_V1[] GetPMGs();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetPcpWithFilters", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetPcpWithFiltersResponse")]
    Mediti2.McoConnector.PcpPmg_V1[] GetPcpWithFilters(System.Nullable<int> managedCareOrganizationID, string carrierID, string pcpFullName, string npi, string specialtyCode, string pmgTaxID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetMcoCapacityById", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetMcoCapacityByIdResponse")]
    Mediti2.McoConnector.SimpleCapacity_V1 GetMcoCapacityById(int mcoID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetMcoCapacityByNumber", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetMcoCapacityByNumberResponse")]
    Mediti2.McoConnector.SimpleCapacity_V1 GetMcoCapacityByNumber(string carrierNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMcoConnector_V1/GetPcpCapacityByNpi", ReplyAction="http://tempuri.org/IMcoConnector_V1/GetPcpCapacityByNpiResponse")]
    Mediti2.McoConnector.SimpleCapacity_V1 GetPcpCapacityByNpi(string mpi);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMcoConnector_V1Channel : IMcoConnector_V1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class McoConnector_V1Client : System.ServiceModel.ClientBase<IMcoConnector_V1>, IMcoConnector_V1
{
    
    public McoConnector_V1Client()
    {
    }
    
    public McoConnector_V1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public McoConnector_V1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public McoConnector_V1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public McoConnector_V1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Mediti2.McoConnector.AppPersonSearchResult_V1 GetApplicationPeopleByMpi(string mpi)
    {
        return base.Channel.GetApplicationPeopleByMpi(mpi);
    }
    
    public Mediti2.McoConnector.AppPersonSearchResult_V1 GetApplicationPeopleByPersonID(int personID)
    {
        return base.Channel.GetApplicationPeopleByPersonID(personID);
    }
    
    public Mediti2.McoConnector.AppPersonSearchResult_V1 GetApplicationPeopleByName(string firstName, string lastName1, string lastName2, string ssnLast4, System.DateTime dateOfBirth)
    {
        return base.Channel.GetApplicationPeopleByName(firstName, lastName1, lastName2, ssnLast4, dateOfBirth);
    }
    
    public Mediti2.McoConnector.AppMemberInfo_V1 GetMediti2AppMembers(int applicationMemberID)
    {
        return base.Channel.GetMediti2AppMembers(applicationMemberID);
    }
    
    public Mediti2.McoConnector.AppPerson_V1[] GetPeople2(string mpi, System.Nullable<int> personID, string firstName, string lastName1, string lastName2, string ssnLast4, System.Nullable<System.DateTime> dateOfBirth)
    {
        return base.Channel.GetPeople2(mpi, personID, firstName, lastName1, lastName2, ssnLast4, dateOfBirth);
    }
    
    public Mediti2.McoConnector.PcpSpecialty_V1[] GetSpecialties()
    {
        return base.Channel.GetSpecialties();
    }
    
    public Mediti2.McoConnector.EnrollmentHistory_V1[] GetEnrollmentChangeHistory(int personID)
    {
        return base.Channel.GetEnrollmentChangeHistory(personID);
    }
    
    public Mediti2.McoConnector.Mco_V1[] GetMcos()
    {
        return base.Channel.GetMcos();
    }
    
    public Mediti2.McoConnector.SimpleEntity_V1[] GetMcosWithCapacity()
    {
        return base.Channel.GetMcosWithCapacity();
    }
    
    public Mediti2.McoConnector.PersonMcoDisplay_V1[] GetApplicationPeople(string applicationNumber)
    {
        return base.Channel.GetApplicationPeople(applicationNumber);
    }
    
    public Mediti2.McoConnector.PersonMcoDisplay_V1 GetPerson(string mpi)
    {
        return base.Channel.GetPerson(mpi);
    }
    
    public Mediti2.McoConnector.PersonMcoDisplay_V1[] GetPeople(string firstName, string lastName1, string lastName2, string ssnLast4, System.DateTime dateOfBirth)
    {
        return base.Channel.GetPeople(firstName, lastName1, lastName2, ssnLast4, dateOfBirth);
    }
    
    public Mediti2.McoConnector.PersonMcoDisplay_V1 SetPersonMco(Mediti2.McoConnector.PersonMco_V1 value, string user, Mediti2.McoConnector.DataSource_V1 source)
    {
        return base.Channel.SetPersonMco(value, user, source);
    }
    
    public Mediti2.McoConnector.PersonMcoDisplay_V1 SetRandomMco(int personID, string user, Mediti2.McoConnector.DataSource_V1 source)
    {
        return base.Channel.SetRandomMco(personID, user, source);
    }
    
    public Mediti2.McoConnector.PcpPmg_V1[] GetPrimaryCarePhysicians()
    {
        return base.Channel.GetPrimaryCarePhysicians();
    }
    
    public Mediti2.McoConnector.Pmg_V1[] GetPMGs()
    {
        return base.Channel.GetPMGs();
    }
    
    public Mediti2.McoConnector.PcpPmg_V1[] GetPcpWithFilters(System.Nullable<int> managedCareOrganizationID, string carrierID, string pcpFullName, string npi, string specialtyCode, string pmgTaxID)
    {
        return base.Channel.GetPcpWithFilters(managedCareOrganizationID, carrierID, pcpFullName, npi, specialtyCode, pmgTaxID);
    }
    
    public Mediti2.McoConnector.SimpleCapacity_V1 GetMcoCapacityById(int mcoID)
    {
        return base.Channel.GetMcoCapacityById(mcoID);
    }
    
    public Mediti2.McoConnector.SimpleCapacity_V1 GetMcoCapacityByNumber(string carrierNumber)
    {
        return base.Channel.GetMcoCapacityByNumber(carrierNumber);
    }
    
    public Mediti2.McoConnector.SimpleCapacity_V1 GetPcpCapacityByNpi(string mpi)
    {
        return base.Channel.GetPcpCapacityByNpi(mpi);
    }
}
